#!/bin/sh

# qwait-clients — Non-web clients for QWait
# Copyright © 2014  Mattias Andrée (maandree@member.fsf.org)
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# USAGE:  qwait-login | qwait-logout
# 
# stdin: Cookies as printed by `qwait-login`


# All cookies.
all_cookies="$(cat)"

# curl arguments for cookies for QWait.
cookies="$(echo "${all_cookies}" | sed -e ':a;N;$!ba;s/\n\n.*//' | sed -e 's/^/-b /')"

# curl arguments for cookies for KTH.
kcookies="$(echo "${all_cookies}" | sed -e ':a;N;$!ba;s/.*\n\n//' | sed -e 's/^/-b /')"

# Logout at QWait!
curl -i -s ${cookies} "http://qwait.csc.kth.se/logout" >/dev/null

# Logout at KTH!
curl -i -s ${kcookies} "https://login.kth.se/logout" >/dev/null

